### ISSUE TITLE
Set the modal iframe style to be of type block

### ISSUE THREAD

**Issue by rang-ali** [pipedrive/app-extensions-sdk#14]
When using the modal view; the iframe style is set to be an inline-element. This causes an empty space at the bottom of the view.

Can we have the iframe style set to be a block-level element? e.g. `display: block`

![image](https://user-images.githubusercontent.com/22007719/228811840-4fa4a381-a456-4d8e-bbb8-eaf89585b530.png)

**Comment by Reivilo85k** [comment]
Hey @rang-ali , sorry for the lack of responsiveness on this issue. I have tried to recreate the same problem but setting `display: block` or not was not causing an empty space anymore. I believed the issue was related to an older version of the SDK and has now been fixed. I will close the issue, but if the issue persists feel free to reopen the issue. We'll be more responsive next time.
